### ISSUE TITLE
 Dialog 关闭不掉

### ISSUE THREAD

**Issue by qiang9420d** [HandyOrg/HandyControl#839] opened 2021-05-27 04:24 UTC
Dialog d = null;
       
        private void Lu_Read(book bk)
        {

            downloadIng dl = new downloadIng(bk);
            dl.downSu += Dl_downSu; ;
            dl.downError += Dl_downError;
            d = Dialog.Show(dl);
        }

        private void Dl_downSu(book bk)
        {
            d.Close();
        }

close()  不生效，不知道是自己用的不对，还是BUG

**Comment by NaBian** [comment] 2021-05-27 06:46
duplicate of #488

**Closed as completed by NaBian** 2021-05-27 06:46 UTC
Labels: :repeat: duplicate
