### ISSUE TITLE
Any Milestone?

### ISSUE THREAD

**Issue by AdarshRise** [HandyOrg/HandyControl#231] opened 2019-11-18 10:07 UTC
Was thinking if there would be  any milestone for this project?

**Comment by NaBian** [comment] 2019-11-18 14:02
no plan is the best plan

**Comment by AdarshRise** [comment] 2019-11-18 17:21
True.

**Comment by AdarshRise** [comment] 2019-11-18 17:37
Though #225  seems to be a good Goal? right?

**Comment by NaBian** [comment] 2019-11-19 15:31
NavigationView is similar to SideMenu in my opinion.

**Comment by AdarshRise** [comment] 2019-11-19 15:53
oh, lol, I wanted to say this 
![image](https://user-images.githubusercontent.com/31347367/69162340-82ccd400-0b12-11ea-98b5-d704ef8ac1eb.png)

a window that quickly explain how to create that control using "hc:xaml", in your Demo of handy tools{ will save a lot of time in going through all docs }.

**Comment by NaBian** [comment] 2019-11-20 12:35
well, it could be Duplicate of #192

**Comment by AdarshRise** [comment] 2019-11-23 04:29
Can't Read Mandarin yet 😅

**Closed as completed** 2019-11-27 14:03 UTC
