### ISSUE TITLE
多选组合框无法二次点击时收回。

### ISSUE THREAD

**Issue by 5653325** [HandyOrg/HandyControl#456] opened 2020-08-10 09:12 UTC
第一次点击为展开，再次点击时无法收回。
![如图](https://img-blog.csdnimg.cn/20200810171119943.gif)

**Comment by ghost1372** [comment] 2020-12-04 11:57
Hi @NaBian 
this way we can solves the problem

```
public static readonly DependencyProperty IsDropDownOpenProperty = DependencyProperty.Register(
            "IsDropDownOpen", typeof(bool), typeof(CheckComboBox), new PropertyMetadata(ValueBoxes.FalseBox, OnValueChanged));

        private static void OnValueChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var ctl = (CheckComboBox)d;
            ctl._popup.IsOpen = (bool)e.NewValue;
        }
```

But as you can see in the picture, the geometry is not updated (I think this problem can be solved easily)
What do you think about this? Is it the right way?

![1](https://user-images.githubusercontent.com/9213496/101161071-40a30180-3645-11eb-8567-5f54bac4866b.gif)

**Comment by ghost1372** [comment] 2020-12-04 15:37
closed by https://github.com/HandyOrg/HandyControl/commit/e4faef32759a9c856a8acbdfad4266fe0c748034

**Comment by ghost1372** [comment] 2020-12-04 15:43
@NaBian 
 oh there is a new problem now We receive an error when the item is selected
```
 <hc:CheckComboBox>
                    <hc:CheckComboBoxItem Content="test"/>
                    <hc:CheckComboBoxItem Content="test"/>
                    <hc:CheckComboBoxItem Content="test"/>
                </hc:CheckComboBox>
```
There is no problem with the ItemSource
![1](https://user-images.githubusercontent.com/9213496/101183347-a5218900-3664-11eb-99f6-f417fcfa6787.png)

**Comment by NaBian** [comment] 2020-12-04 15:45
there is an other new problem, when the popup is opened, it can not be closed by clicking on the blank area

**Comment by NaBian** [comment] 2020-12-04 15:48
I've spent an hour solving the problem, bad result as last, I' m tired and need to sleep

**Comment by ghost1372** [comment] 2020-12-04 15:52
@ghost1372  ok Go get some rest.
Iran is 7.20 pm I'm still awake to see if I can find a way😅

**Comment by ghost1372** [comment] 2020-12-04 18:24
According to [this](https://stackoverflow.com/a/53706500/13024846) reference, I wrote the following code
path: `CheckComboBox.cs\UpdateTags()
`
```
if (tag.Content != null)
                    {
                        var test = tag as Tag;
                        tag.Content = null;
                        _panel.Children.Add(test);

                    }
```
The problem is solved but the tags do not have text😂

**Comment by ghost1372** [comment] 2021-01-31 14:10
@NaBian issue fixed after https://github.com/HandyOrg/HandyControl/commit/667465a375add8a841a821e92027b3a1ee4478b0

but this issue exist

> @NaBian
> oh there is a new problem now We receive an error when the item is selected
> 
> ```
>  <hc:CheckComboBox>
>                     <hc:CheckComboBoxItem Content="test"/>
>                     <hc:CheckComboBoxItem Content="test"/>
>                     <hc:CheckComboBoxItem Content="test"/>
>                 </hc:CheckComboBox>
> ```
> 
> There is no problem with the ItemSource
> ![1](https://user-images.githubusercontent.com/9213496/101183347-a5218900-3664-11eb-99f6-f417fcfa6787.png)

**Comment by NaBian** [comment] 2021-01-31 16:02
drop down checkcombobox then keep it open finally drag the window, aha a new bug!

**Closed as completed** 2021-02-01 16:27 UTC
Labels: :bug: bug, :art: design defect

**Comment by ghost1372** [comment] 2021-02-01 16:47
@NaBian 
drop down issue fixed but
without binding not work
```
<hc:CheckComboBox>
    <hc:CheckComboBoxItem Content="test"/>
    <hc:CheckComboBoxItem Content="test"/>
    <hc:CheckComboBoxItem Content="test"/>
</hc:CheckComboBox>
```
![image](https://user-images.githubusercontent.com/9213496/106489747-552b3b00-64ca-11eb-9702-fb0e747ba022.png)

**Comment by NaBian** [comment] 2021-02-03 13:55
done in 2b1973fd

**Comment by ghost1372** [comment] 2021-02-03 14:27
@NaBian Did you try?
Because I get the same result as before

**Comment by NaBian** [comment] 2021-02-03 15:21
> @NaBian Did you try?
> Because I get the same result as before

of course
![demo](https://user-images.githubusercontent.com/17383395/106767971-6add6380-6676-11eb-8a49-c8c5c7be91b0.gif)

**Comment by ghost1372** [comment] 2021-02-03 15:24
your fix not worked for me i changed your if statement **!=** to **==** and worked!😶

**Comment by NaBian** [comment] 2021-02-03 15:27
what? why?

**Comment by ghost1372** [comment] 2021-02-03 15:27
> what? why?
see
![1](https://user-images.githubusercontent.com/9213496/106768738-75393680-6651-11eb-927f-e2821601864e.gif)
![2](https://user-images.githubusercontent.com/9213496/106768837-96018c00-6651-11eb-9473-1934a21a82f5.gif)

**Comment by NaBian** [comment] 2021-02-03 15:30
😭

**Comment by ghost1372** [comment] 2021-02-03 15:45
@NaBian This is very strange
I tested on a new project, there is no problem worked fine
But there is a problem in the demo project
