### ISSUE TITLE
[HandyOrg/HandyControl] DataGridComboBoxColumn DropDown arrow is not shown

### ISSUE THREAD

**Issue by MohammadRezaKashi** [HandyOrg/HandyControl#539] opened 2020-12-01 16:20 UTC
When I want to use Handy Theme for just one WPF user control, not for all application, this problem appears.
this is my code:
XAML:
```
<Window x:Class="DataGridTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:hc="https://handyorg.github.io/handycontrol"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">


    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <hc:Theme Skin="Dark" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
   
    <hc:TransitioningContentControl>
        <DataGrid x:Name="DataGrid" RowHeaderWidth="60"></DataGrid>
    </hc:TransitioningContentControl>
</Window>
```

c#:
```
using System.Collections.Generic;
using System.Windows;

namespace DataGridTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            this.DataGrid.ItemsSource = GetDemoDataList();
        }

        internal List<DemoDataModel> GetDemoDataList()
        {
            var list = new List<DemoDataModel>();
            for (var i = 1; i <= 20; i++)
            {
                var dataList = new List<DemoDataModel>();
                for (var j = 0; j < 3; j++)
                {
                    dataList.Add(new DemoDataModel
                    {
                        Index = j,
                        IsSelected = j % 2 == 0,
                        Name = $"SubName{j}",
                        Type = ""
                    });
                }
                var model = new DemoDataModel
                {
                    Index = i,
                    IsSelected = i % 2 == 0,
                    Name = $"Name{i}",
                    Type = "",
                    DataList = dataList,
                    ImgPath = $"/HandyControlDemo;component/Resources/Img/Avatar/avatar{i % 6 + 1}.png",
                    Remark = new string(i.ToString()[0], 10)
                };
                list.Add(model);
            }

            return list;
        }
    }

    public enum OrderStatus { None, New, Processing, Shipped, Received };
    public class DemoDataModel
    {
        public int Index { get; set; }

        public string Name { get; set; }

        public bool IsSelected { get; set; }

        public string Remark { get; set; }

        public string Type { get; set; }

        public string ImgPath { get; set; }

        public OrderStatus combox { get; set; }

        public List<DemoDataModel> DataList { get; set; }
    }
}
```

and this is my App.xaml:

```
<Application x:Class="DataGridTest.App" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:local="clr-namespace:DataGridTest" StartupUri="MainWindow.xaml">
  <Application.Resources>
    <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
                <!--<hc:Theme Name="HandyTheme" xmlns:hc="https://handyorg.github.io/handycontrol" Skin="Dark"/>-->
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

and the result is attached.
![error](https://user-images.githubusercontent.com/52103513/100766768-44007800-340e-11eb-89a2-47d9c9d6ed01.png)

**Comment by NaBian** [comment] 2021-01-16 10:43
duplicate of #499

**Closed as completed by NaBian** 2021-01-16 10:43 UTC
Labels: :repeat: duplicate
